# Generated by Django 3.0.7 on 2020-08-10 23:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pocos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=254, verbose_name='proprietario')),
                ('orgao', models.CharField(max_length=254, verbose_name='orgao')),
                ('data_perfuracao', models.DateField(verbose_name='data_perfuracao')),
                ('profundidade', models.FloatField(verbose_name='profundidade')),
                ('q_m3h', models.FloatField(verbose_name='q_m3h')),
                ('equipamento', models.CharField(max_length=254, verbose_name='equipamento')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
            ],
        ),
    ]
